using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Category : System.Web.UI.Page
{    
    protected void Page_Load(object sender, EventArgs e)
    {        
        if (!Page.IsPostBack)
        {
            Cat_Bind();
            Latest();
            mostPopular();
        }        
    }
    private void Cat_Bind()
    {
        string cat = RouteData.Values["cat"].ToString();        
        if (cat == "Technology")
        {
            category.Text = "Technology";
            load.Text = "Technology";
            string Format = "MMMM d, yyyy";
            String qry = "select TOP 10 techcod, techhed, techdis2, techimg, techcat, techdate, techautcod from tech order by techdate DESC; select * from tech";
            SqlDataAdapter adp = new SqlDataAdapter(qry, ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            DataRowView r;
            r = ds.Tables[0].DefaultView[0];
            ccod1.Text = r["techcod"].ToString();
            cimg1.ImageUrl = r["techimg"].ToString();
            ched1.Text = r["techhed"].ToString();
            cdis1.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat1.Text = r["techcat"].ToString();
            cimg1.AlternateText = ched1.Text + " - KNine Vox";
            var date = Convert.ToDateTime(r["techdate"]);
            cdate1.Text = date.ToString(Format);
            caut1.Text = Author1(Convert.ToInt32(r["techautcod"]));
            r = ds.Tables[0].DefaultView[1];
            ccod2.Text = r["techcod"].ToString();
            cimg2.ImageUrl = r["techimg"].ToString();
            ched2.Text = r["techhed"].ToString();
            cdis2.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat2.Text = r["techcat"].ToString();
            cimg2.AlternateText = ched2.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["techdate"]);
            cdate2.Text = date.ToString(Format);
            caut2.Text = Author1(Convert.ToInt32(r["techautcod"]));
            r = ds.Tables[0].DefaultView[2];
            ccod3.Text = r["techcod"].ToString();
            cimg3.ImageUrl = r["techimg"].ToString();
            ched3.Text = r["techhed"].ToString();
            cdis3.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat3.Text = r["techcat"].ToString();
            cimg3.AlternateText = ched3.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["techdate"]);
            cdate3.Text = date.ToString(Format);
            caut3.Text = Author1(Convert.ToInt32(r["techautcod"]));
            r = ds.Tables[0].DefaultView[3];
            ccod4.Text = r["techcod"].ToString();
            cimg4.ImageUrl = r["techimg"].ToString();
            ched4.Text = r["techhed"].ToString();
            cdis4.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat4.Text = r["techcat"].ToString();
            cimg4.AlternateText = ched4.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["techdate"]);
            cdate4.Text = date.ToString(Format);
            caut4.Text = Author1(Convert.ToInt32(r["techautcod"]));
            r = ds.Tables[0].DefaultView[4];
            ccod5.Text = r["techcod"].ToString();
            cimg5.ImageUrl = r["techimg"].ToString();
            ched5.Text = r["techhed"].ToString();
            cdis5.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat5.Text = r["techcat"].ToString();
            cimg5.AlternateText = ched5.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["techdate"]);
            cdate5.Text = date.ToString(Format);
            caut5.Text = Author1(Convert.ToInt32(r["techautcod"]));
            r = ds.Tables[0].DefaultView[5];
            ccod6.Text = r["techcod"].ToString();
            cimg6.ImageUrl = r["techimg"].ToString();
            ched6.Text = r["techhed"].ToString();
            cdis6.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat6.Text = r["techcat"].ToString();
            cimg6.AlternateText = ched6.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["techdate"]);
            cdate6.Text = date.ToString(Format);
            caut6.Text = Author1(Convert.ToInt32(r["techautcod"]));
            r = ds.Tables[0].DefaultView[6];
            ccod7.Text = r["techcod"].ToString();
            cimg7.ImageUrl = r["techimg"].ToString();
            ched7.Text = r["techhed"].ToString();
            cdis7.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat7.Text = r["techcat"].ToString();
            cimg7.AlternateText = ched7.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["techdate"]);
            cdate7.Text = date.ToString(Format);
            caut7.Text = Author1(Convert.ToInt32(r["techautcod"]));
            r = ds.Tables[0].DefaultView[7];
            ccod8.Text = r["techcod"].ToString();
            cimg8.ImageUrl = r["techimg"].ToString();
            ched8.Text = r["techhed"].ToString();
            cdis8.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat8.Text = r["techcat"].ToString();
            cimg8.AlternateText = ched8.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["techdate"]);
            cdate8.Text = date.ToString(Format);
            caut8.Text = Author1(Convert.ToInt32(r["techautcod"]));
            r = ds.Tables[0].DefaultView[8];
            ccod9.Text = r["techcod"].ToString();
            cimg9.ImageUrl = r["techimg"].ToString();
            ched9.Text = r["techhed"].ToString();
            cdis9.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat9.Text = r["techcat"].ToString();
            cimg9.AlternateText = ched9.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["techdate"]);
            cdate9.Text = date.ToString(Format);
            caut9.Text = Author1(Convert.ToInt32(r["techautcod"]));
            r = ds.Tables[0].DefaultView[9];
            ccod10.Text = r["techcod"].ToString();
            cimg10.ImageUrl = r["techimg"].ToString();
            ched10.Text = r["techhed"].ToString();
            cdis10.Text = "<span>«" + r["techdis2"].ToString() + "»</span>";
            ccat10.Text = r["techcat"].ToString();
            cimg10.AlternateText = ched10.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["techdate"]);
            cdate10.Text = date.ToString(Format);
            caut10.Text = Author1(Convert.ToInt32(r["techautcod"]));
            num.Text = "(" + ds.Tables[1].Rows.Count.ToString() + ")";
        }
        else if (cat == "Science")
        {
            category.Text = "Science";
            load.Text = "Science";
            string Format = "MMMM d, yyyy";
            String qry = "select TOP 10 scicod, scihed, scidis2, sciimg, scicat, scidate, sciautcod from sci order by scidate DESC; select * from sci";
            SqlDataAdapter adp = new SqlDataAdapter(qry, ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            DataRowView r;
            r = ds.Tables[0].DefaultView[0];
            ccod1.Text = r["scicod"].ToString();
            cimg1.ImageUrl = r["sciimg"].ToString();
            ched1.Text = r["scihed"].ToString();
            cdis1.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat1.Text = r["scicat"].ToString();
            cimg1.AlternateText = ched1.Text + " - KNine Vox";
            var date = Convert.ToDateTime(r["scidate"]);
            cdate1.Text = date.ToString(Format);
            caut1.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            r = ds.Tables[0].DefaultView[1];
            ccod2.Text = r["scicod"].ToString();
            cimg2.ImageUrl = r["sciimg"].ToString();
            ched2.Text = r["scihed"].ToString();
            cdis2.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat2.Text = r["scicat"].ToString();
            cimg2.AlternateText = ched2.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["scidate"]);
            cdate2.Text = date.ToString(Format);
            caut2.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            r = ds.Tables[0].DefaultView[2];
            ccod3.Text = r["scicod"].ToString();
            cimg3.ImageUrl = r["sciimg"].ToString();
            ched3.Text = r["scihed"].ToString();
            cdis3.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat3.Text = r["scicat"].ToString();
            cimg3.AlternateText = ched3.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["scidate"]);
            cdate3.Text = date.ToString(Format);
            caut3.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            r = ds.Tables[0].DefaultView[3];
            ccod4.Text = r["scicod"].ToString();
            cimg4.ImageUrl = r["sciimg"].ToString();
            ched4.Text = r["scihed"].ToString();
            cdis4.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat4.Text = r["scicat"].ToString();
            cimg4.AlternateText = ched4.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["scidate"]);
            cdate4.Text = date.ToString(Format);
            caut4.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            r = ds.Tables[0].DefaultView[4];
            ccod5.Text = r["scicod"].ToString();
            cimg5.ImageUrl = r["sciimg"].ToString();
            ched5.Text = r["scihed"].ToString();
            cdis5.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat5.Text = r["scicat"].ToString();
            cimg5.AlternateText = ched5.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["scidate"]);
            cdate5.Text = date.ToString(Format);
            caut5.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            r = ds.Tables[0].DefaultView[5];
            ccod6.Text = r["scicod"].ToString();
            cimg6.ImageUrl = r["sciimg"].ToString();
            ched6.Text = r["scihed"].ToString();
            cdis6.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat6.Text = r["scicat"].ToString();
            cimg6.AlternateText = ched6.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["scidate"]);
            cdate6.Text = date.ToString(Format);
            caut6.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            r = ds.Tables[0].DefaultView[6];
            ccod7.Text = r["scicod"].ToString();
            cimg7.ImageUrl = r["sciimg"].ToString();
            ched7.Text = r["scihed"].ToString();
            cdis7.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat7.Text = r["scicat"].ToString();
            cimg7.AlternateText = ched7.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["scidate"]);
            cdate7.Text = date.ToString(Format);
            caut7.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            r = ds.Tables[0].DefaultView[7];
            ccod8.Text = r["scicod"].ToString();
            cimg8.ImageUrl = r["sciimg"].ToString();
            ched8.Text = r["scihed"].ToString();
            cdis8.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat8.Text = r["scicat"].ToString();
            cimg8.AlternateText = ched8.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["scidate"]);
            cdate8.Text = date.ToString(Format);
            caut8.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            r = ds.Tables[0].DefaultView[8];
            ccod9.Text = r["scicod"].ToString();
            cimg9.ImageUrl = r["sciimg"].ToString();
            ched9.Text = r["scihed"].ToString();
            cdis9.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat9.Text = r["scicat"].ToString();
            cimg9.AlternateText = ched9.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["scidate"]);
            cdate9.Text = date.ToString(Format);
            caut9.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            r = ds.Tables[0].DefaultView[9];
            ccod10.Text = r["scicod"].ToString();
            cimg10.ImageUrl = r["sciimg"].ToString();
            ched10.Text = r["scihed"].ToString();
            cdis10.Text = "<span>«" + r["scidis2"].ToString() + "»</span>";
            ccat10.Text = r["scicat"].ToString();
            cimg10.AlternateText = ched10.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["scidate"]);
            cdate10.Text = date.ToString(Format);
            caut10.Text = Author1(Convert.ToInt32(r["sciautcod"]));
            num.Text = "(" + ds.Tables[1].Rows.Count.ToString() + ")";
        }
        else if (cat == "Games")
        {
            category.Text = "Games";
            load.Text = "Games";
            string Format = "MMMM d, yyyy";
            String qry = "select TOP 10 gamcod, gamhed, gamdis2, gamimg, gamcat, gamdate, gamautcod from games order by gamdate DESC; select * from games";
            SqlDataAdapter adp = new SqlDataAdapter(qry, ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            DataRowView r;
            r = ds.Tables[0].DefaultView[0];
            ccod1.Text = r["gamcod"].ToString();
            cimg1.ImageUrl = r["gamimg"].ToString();
            ched1.Text = r["gamhed"].ToString();
            cdis1.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            ccat1.Text = r["gamcat"].ToString();
            cimg1.AlternateText = ched1.Text + " - KNine Vox";
            var date = Convert.ToDateTime(r["gamdate"]);
            cdate1.Text = date.ToString(Format);
            caut1.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            r = ds.Tables[0].DefaultView[1];
            ccod2.Text = r["gamcod"].ToString();
            cimg2.ImageUrl = r["gamimg"].ToString();
            ched2.Text = r["gamhed"].ToString();
            cdis2.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            ccat2.Text = r["gamcat"].ToString();
            cimg2.AlternateText = ched2.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["gamdate"]);
            cdate2.Text = date.ToString(Format);
            caut2.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            r = ds.Tables[0].DefaultView[2];
            ccod3.Text = r["gamcod"].ToString();
            cimg3.ImageUrl = r["gamimg"].ToString();
            ched3.Text = r["gamhed"].ToString();
            cdis3.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            ccat3.Text = r["gamcat"].ToString();
            cimg3.AlternateText = ched3.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["gamdate"]);
            cdate3.Text = date.ToString(Format);
            caut3.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            r = ds.Tables[0].DefaultView[3];
            ccod4.Text = r["gamcod"].ToString();
            cimg4.ImageUrl = r["gamimg"].ToString();
            ched4.Text = r["gamhed"].ToString();
            cdis4.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            ccat4.Text = r["gamcat"].ToString();
            cimg4.AlternateText = ched4.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["gamdate"]);
            cdate4.Text = date.ToString(Format);
            caut4.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            r = ds.Tables[0].DefaultView[4];
            ccod5.Text = r["gamcod"].ToString();
            cimg5.ImageUrl = r["gamimg"].ToString();
            ched5.Text = r["gamhed"].ToString();
            cdis5.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            ccat5.Text = r["gamcat"].ToString();
            cimg5.AlternateText = ched5.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["gamdate"]);
            cdate5.Text = date.ToString(Format);
            caut5.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            r = ds.Tables[0].DefaultView[5];
            ccod6.Text = r["gamcod"].ToString();
            cimg6.ImageUrl = r["gamimg"].ToString();
            ched6.Text = r["gamhed"].ToString();
            cdis6.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            ccat6.Text = r["gamcat"].ToString();
            cimg6.AlternateText = ched6.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["gamdate"]);
            cdate6.Text = date.ToString(Format);
            caut6.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            //r = ds.Tables[0].DefaultView[6];
            //ccod7.Text = r["gamcod"].ToString();
            //cimg7.ImageUrl = r["gamimg"].ToString();
            //ched7.Text = r["gamhed"].ToString();
            //cdis7.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            //ccat7.Text = r["gamcat"].ToString();
            //cimg7.AlternateText = ched7.Text + " - KNine Vox";
            //date = Convert.ToDateTime(r["gamdate"]);
            //cdate7.Text = date.ToString(Format);
            //caut7.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            //r = ds.Tables[0].DefaultView[7];
            //ccod8.Text = r["gamcod"].ToString();
            //cimg8.ImageUrl = r["gamimg"].ToString();
            //ched8.Text = r["gamhed"].ToString();
            //cdis8.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            //ccat8.Text = r["gamcat"].ToString();
            //cimg8.AlternateText = ched8.Text + " - KNine Vox";
            //date = Convert.ToDateTime(r["gamdate"]);
            //cdate8.Text = date.ToString(Format);
            //caut8.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            //r = ds.Tables[0].DefaultView[8];
            //ccod9.Text = r["gamcod"].ToString();
            //cimg9.ImageUrl = r["gamimg"].ToString();
            //ched9.Text = r["gamhed"].ToString();
            //cdis9.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            //ccat9.Text = r["gamcat"].ToString();
            //cimg9.AlternateText = ched9.Text + " - KNine Vox";
            //date = Convert.ToDateTime(r["gamdate"]);
            //cdate9.Text = date.ToString(Format);
            //caut9.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            //r = ds.Tables[0].DefaultView[9];
            //ccod10.Text = r["gamcod"].ToString();
            //cimg10.ImageUrl = r["gamimg"].ToString();
            //ched10.Text = r["gamhed"].ToString();
            //cdis10.Text = "<span>«" + r["gamdis2"].ToString() + "»</span>";
            //ccat10.Text = r["gamcat"].ToString();
            //cimg10.AlternateText = ched10.Text + " - KNine Vox";
            //date = Convert.ToDateTime(r["gamdate"]);
            //cdate10.Text = date.ToString(Format);
            //caut10.Text = Author1(Convert.ToInt32(r["gamautcod"]));
            num.Text = "(" + ds.Tables[1].Rows.Count.ToString() + ")";
        }
        else if (cat == "Sports")
        {
            category.Text = "Sports";
            load.Text = "Sports";
            string Format = "MMMM d, yyyy";
            String qry = "select TOP 10 spcod, sphed, spdis2, spimg, spcat, spdate, spautcod from sports order by spdate DESC; select * from sports";
            SqlDataAdapter adp = new SqlDataAdapter(qry, ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            DataRowView r;
            r = ds.Tables[0].DefaultView[0];
            ccod1.Text = r["spcod"].ToString();
            cimg1.ImageUrl = r["spimg"].ToString();
            ched1.Text = r["sphed"].ToString();
            cdis1.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat1.Text = r["spcat"].ToString();
            cimg1.AlternateText = ched1.Text + " - KNine Vox";
            var date = Convert.ToDateTime(r["spdate"]);
            cdate1.Text = date.ToString(Format);
            caut1.Text = Author1(Convert.ToInt32(r["spautcod"]));
            r = ds.Tables[0].DefaultView[1];
            ccod2.Text = r["spcod"].ToString();
            cimg2.ImageUrl = r["spimg"].ToString();
            ched2.Text = r["sphed"].ToString();
            cdis2.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat2.Text = r["spcat"].ToString();
            cimg2.AlternateText = ched2.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["spdate"]);
            cdate2.Text = date.ToString(Format);
            caut2.Text = Author1(Convert.ToInt32(r["spautcod"]));
            r = ds.Tables[0].DefaultView[2];
            ccod3.Text = r["spcod"].ToString();
            cimg3.ImageUrl = r["spimg"].ToString();
            ched3.Text = r["sphed"].ToString();
            cdis3.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat3.Text = r["spcat"].ToString();
            cimg3.AlternateText = ched3.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["spdate"]);
            cdate3.Text = date.ToString(Format);
            caut3.Text = Author1(Convert.ToInt32(r["spautcod"]));
            r = ds.Tables[0].DefaultView[3];
            ccod4.Text = r["spcod"].ToString();
            cimg4.ImageUrl = r["spimg"].ToString();
            ched4.Text = r["sphed"].ToString();
            cdis4.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat4.Text = r["spcat"].ToString();
            cimg4.AlternateText = ched4.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["spdate"]);
            cdate4.Text = date.ToString(Format);
            caut4.Text = Author1(Convert.ToInt32(r["spautcod"]));
            r = ds.Tables[0].DefaultView[4];
            ccod5.Text = r["spcod"].ToString();
            cimg5.ImageUrl = r["spimg"].ToString();
            ched5.Text = r["sphed"].ToString();
            cdis5.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat5.Text = r["spcat"].ToString();
            cimg5.AlternateText = ched5.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["spdate"]);
            cdate5.Text = date.ToString(Format);
            caut5.Text = Author1(Convert.ToInt32(r["spautcod"]));
            r = ds.Tables[0].DefaultView[5];
            ccod6.Text = r["spcod"].ToString();
            cimg6.ImageUrl = r["spimg"].ToString();
            ched6.Text = r["sphed"].ToString();
            cdis6.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat6.Text = r["spcat"].ToString();
            cimg6.AlternateText = ched6.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["spdate"]);
            cdate6.Text = date.ToString(Format);
            caut6.Text = Author1(Convert.ToInt32(r["spautcod"]));
            r = ds.Tables[0].DefaultView[6];
            ccod7.Text = r["spcod"].ToString();
            cimg7.ImageUrl = r["spimg"].ToString();
            ched7.Text = r["sphed"].ToString();
            cdis7.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat7.Text = r["spcat"].ToString();
            cimg7.AlternateText = ched7.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["spdate"]);
            cdate7.Text = date.ToString(Format);
            caut7.Text = Author1(Convert.ToInt32(r["spautcod"]));
            r = ds.Tables[0].DefaultView[7];
            ccod8.Text = r["spcod"].ToString();
            cimg8.ImageUrl = r["spimg"].ToString();
            ched8.Text = r["sphed"].ToString();
            cdis8.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat8.Text = r["spcat"].ToString();
            cimg8.AlternateText = ched8.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["spdate"]);
            cdate8.Text = date.ToString(Format);
            caut8.Text = Author1(Convert.ToInt32(r["spautcod"]));
            r = ds.Tables[0].DefaultView[8];
            ccod9.Text = r["spcod"].ToString();
            cimg9.ImageUrl = r["spimg"].ToString();
            ched9.Text = r["sphed"].ToString();
            cdis9.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat9.Text = r["spcat"].ToString();
            cimg9.AlternateText = ched9.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["spdate"]);
            cdate9.Text = date.ToString(Format);
            caut9.Text = Author1(Convert.ToInt32(r["spautcod"]));
            r = ds.Tables[0].DefaultView[9];
            ccod10.Text = r["spcod"].ToString();
            cimg10.ImageUrl = r["spimg"].ToString();
            ched10.Text = r["sphed"].ToString();
            cdis10.Text = "<span>«" + r["spdis2"].ToString() + "»</span>";
            ccat10.Text = r["spcat"].ToString();
            cimg10.AlternateText = ched10.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["spdate"]);
            cdate10.Text = date.ToString(Format);
            caut10.Text = Author1(Convert.ToInt32(r["spautcod"]));
            num.Text = "(" + ds.Tables[1].Rows.Count.ToString() + ")";
        }
        else if (cat == "Entertainment")
        {
            category.Text = "Entertainment";
            load.Text = "Entertainment";
            string Format = "MMMM d, yyyy";
            String qry = "select TOP 10 entercod, enterhed, enterdis2, enterimg, entercat, enterdate, enterautcod from enter order by enterdate DESC;select * from enter";
            SqlDataAdapter adp = new SqlDataAdapter(qry, ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            DataRowView r;
            r = ds.Tables[0].DefaultView[0];
            ccod1.Text = r["entercod"].ToString();
            cimg1.ImageUrl = r["enterimg"].ToString();
            ched1.Text = r["enterhed"].ToString();
            cdis1.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            ccat1.Text = r["entercat"].ToString();
            cimg1.AlternateText = ched1.Text + " - KNine Vox";
            var date = Convert.ToDateTime(r["enterdate"]);
            cdate1.Text = date.ToString(Format);
            caut1.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            r = ds.Tables[0].DefaultView[1];
            ccod2.Text = r["entercod"].ToString();
            cimg2.ImageUrl = r["enterimg"].ToString();
            ched2.Text = r["enterhed"].ToString();
            cdis2.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            ccat2.Text = r["entercat"].ToString();
            cimg2.AlternateText = ched2.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["enterdate"]);
            cdate2.Text = date.ToString(Format);
            caut2.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            r = ds.Tables[0].DefaultView[2];
            ccod3.Text = r["entercod"].ToString();
            cimg3.ImageUrl = r["enterimg"].ToString();
            ched3.Text = r["enterhed"].ToString();
            cdis3.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            ccat3.Text = r["entercat"].ToString();
            cimg3.AlternateText = ched3.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["enterdate"]);
            cdate3.Text = date.ToString(Format);
            caut3.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            r = ds.Tables[0].DefaultView[3];
            ccod4.Text = r["entercod"].ToString();
            cimg4.ImageUrl = r["enterimg"].ToString();
            ched4.Text = r["enterhed"].ToString();
            cdis4.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            ccat4.Text = r["entercat"].ToString();
            cimg4.AlternateText = ched4.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["enterdate"]);
            cdate4.Text = date.ToString(Format);
            caut4.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            r = ds.Tables[0].DefaultView[4];
            ccod5.Text = r["entercod"].ToString();
            cimg5.ImageUrl = r["enterimg"].ToString();
            ched5.Text = r["enterhed"].ToString();
            cdis5.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            ccat5.Text = r["entercat"].ToString();
            cimg5.AlternateText = ched5.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["enterdate"]);
            cdate5.Text = date.ToString(Format);
            caut5.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            r = ds.Tables[0].DefaultView[5];
            ccod6.Text = r["entercod"].ToString();
            cimg6.ImageUrl = r["enterimg"].ToString();
            ched6.Text = r["enterhed"].ToString();
            cdis6.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            ccat6.Text = r["entercat"].ToString();
            cimg6.AlternateText = ched6.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["enterdate"]);
            cdate6.Text = date.ToString(Format);
            caut6.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            r = ds.Tables[0].DefaultView[6];
            ccod7.Text = r["entercod"].ToString();
            cimg7.ImageUrl = r["enterimg"].ToString();
            ched7.Text = r["enterhed"].ToString();
            cdis7.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            ccat7.Text = r["entercat"].ToString();
            cimg7.AlternateText = ched7.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["enterdate"]);
            cdate7.Text = date.ToString(Format);
            caut7.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            r = ds.Tables[0].DefaultView[7];
            ccod8.Text = r["entercod"].ToString();
            cimg8.ImageUrl = r["enterimg"].ToString();
            ched8.Text = r["enterhed"].ToString();
            cdis8.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            ccat8.Text = r["entercat"].ToString();
            cimg8.AlternateText = ched8.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["enterdate"]);
            cdate8.Text = date.ToString(Format);
            caut8.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            r = ds.Tables[0].DefaultView[8];
            ccod9.Text = r["entercod"].ToString();
            cimg9.ImageUrl = r["enterimg"].ToString();
            ched9.Text = r["enterhed"].ToString();
            cdis9.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            ccat9.Text = r["entercat"].ToString();
            cimg9.AlternateText = ched9.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["enterdate"]);
            cdate9.Text = date.ToString(Format);
            caut9.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            //r = ds.Tables[0].DefaultView[9];
            //ccod10.Text = r["entercod"].ToString();
            //cimg10.ImageUrl = r["enterimg"].ToString();
            //ched10.Text = r["enterhed"].ToString();
            //cdis10.Text = "<span>«" + r["enterdis2"].ToString() + "»</span>";
            //ccat10.Text = r["entercat"].ToString();
            //cimg10.AlternateText = ched10.Text + " - KNine Vox";
            //date = Convert.ToDateTime(r["enterdate"]);
            //cdate10.Text = date.ToString(Format);
            //caut10.Text = Author1(Convert.ToInt32(r["enterautcod"]));
            num.Text = "(" + ds.Tables[1].Rows.Count.ToString() + ")";
        }
        else if (cat == "App")
        {
            category.Text = "App & Software";
            load.Text = "App";
            string Format = "MMMM d, yyyy";
            String qry = "select TOP 10 appcod, apphed, appdis2, appimg, appcat, appdate, appautcod from app order by appdate DESC; select * from app";
            SqlDataAdapter adp = new SqlDataAdapter(qry, ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            DataRowView r;
            r = ds.Tables[0].DefaultView[0];
            ccod1.Text = r["appcod"].ToString();
            cimg1.ImageUrl = r["appimg"].ToString();
            ched1.Text = r["apphed"].ToString();
            cdis1.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat1.Text = r["appcat"].ToString();
            cimg1.AlternateText = ched1.Text + " - KNine Vox";
            var date = Convert.ToDateTime(r["appdate"]);
            cdate1.Text = date.ToString(Format);
            caut1.Text = Author1(Convert.ToInt32(r["appautcod"]));
            r = ds.Tables[0].DefaultView[1];
            ccod2.Text = r["appcod"].ToString();
            cimg2.ImageUrl = r["appimg"].ToString();
            ched2.Text = r["apphed"].ToString();
            cdis2.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat2.Text = r["appcat"].ToString();
            cimg2.AlternateText = ched2.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["appdate"]);
            cdate2.Text = date.ToString(Format);
            caut2.Text = Author1(Convert.ToInt32(r["appautcod"]));
            r = ds.Tables[0].DefaultView[2];
            ccod3.Text = r["appcod"].ToString();
            cimg3.ImageUrl = r["appimg"].ToString();
            ched3.Text = r["apphed"].ToString();
            cdis3.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat3.Text = r["appcat"].ToString();
            cimg3.AlternateText = ched3.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["appdate"]);
            cdate3.Text = date.ToString(Format);
            caut3.Text = Author1(Convert.ToInt32(r["appautcod"]));
            r = ds.Tables[0].DefaultView[3];
            ccod4.Text = r["appcod"].ToString();
            cimg4.ImageUrl = r["appimg"].ToString();
            ched4.Text = r["apphed"].ToString();
            cdis4.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat4.Text = r["appcat"].ToString();
            cimg4.AlternateText = ched4.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["appdate"]);
            cdate4.Text = date.ToString(Format);
            caut4.Text = Author1(Convert.ToInt32(r["appautcod"]));
            r = ds.Tables[0].DefaultView[4];
            ccod5.Text = r["appcod"].ToString();
            cimg5.ImageUrl = r["appimg"].ToString();
            ched5.Text = r["apphed"].ToString();
            cdis5.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat5.Text = r["appcat"].ToString();
            cimg5.AlternateText = ched5.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["appdate"]);
            cdate5.Text = date.ToString(Format);
            caut5.Text = Author1(Convert.ToInt32(r["appautcod"]));
            r = ds.Tables[0].DefaultView[5];
            ccod6.Text = r["appcod"].ToString();
            cimg6.ImageUrl = r["appimg"].ToString();
            ched6.Text = r["apphed"].ToString();
            cdis6.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat6.Text = r["appcat"].ToString();
            cimg6.AlternateText = ched6.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["appdate"]);
            cdate6.Text = date.ToString(Format);
            caut6.Text = Author1(Convert.ToInt32(r["appautcod"]));
            r = ds.Tables[0].DefaultView[6];
            ccod7.Text = r["appcod"].ToString();
            cimg7.ImageUrl = r["appimg"].ToString();
            ched7.Text = r["apphed"].ToString();
            cdis7.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat7.Text = r["appcat"].ToString();
            cimg7.AlternateText = ched7.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["appdate"]);
            cdate7.Text = date.ToString(Format);
            caut7.Text = Author1(Convert.ToInt32(r["appautcod"]));
            r = ds.Tables[0].DefaultView[7];
            ccod8.Text = r["appcod"].ToString();
            cimg8.ImageUrl = r["appimg"].ToString();
            ched8.Text = r["apphed"].ToString();
            cdis8.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat8.Text = r["appcat"].ToString();
            cimg8.AlternateText = ched8.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["appdate"]);
            cdate8.Text = date.ToString(Format);
            caut8.Text = Author1(Convert.ToInt32(r["appautcod"]));
            r = ds.Tables[0].DefaultView[8];
            ccod9.Text = r["appcod"].ToString();
            cimg9.ImageUrl = r["appimg"].ToString();
            ched9.Text = r["apphed"].ToString();
            cdis9.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat9.Text = r["appcat"].ToString();
            cimg9.AlternateText = ched9.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["appdate"]);
            cdate9.Text = date.ToString(Format);
            caut9.Text = Author1(Convert.ToInt32(r["appautcod"]));
            r = ds.Tables[0].DefaultView[9];
            ccod10.Text = r["appcod"].ToString();
            cimg10.ImageUrl = r["appimg"].ToString();
            ched10.Text = r["apphed"].ToString();
            cdis10.Text = "<span>«" + r["appdis2"].ToString() + "»</span>";
            ccat10.Text = r["appcat"].ToString();
            cimg10.AlternateText = ched10.Text + " - KNine Vox";
            date = Convert.ToDateTime(r["appdate"]);
            cdate10.Text = date.ToString(Format);
            caut10.Text = Author1(Convert.ToInt32(r["appautcod"]));
            num.Text = "(" + ds.Tables[1].Rows.Count.ToString() + ")";
        }
        else
        {
            Server.Transfer("404.aspx");
        }
    }
    private void Latest()
    {
        String qry = "select TOP 7 mjcod, mjhed, mjimg, mjdate, mjcat FROM ( select TOP 7 techcod mjcod, techhed mjhed, techimg mjimg, techdate mjdate, techcat mjcat from tech order by techdate DESC UNION ALL select TOP 7 scicod mjcod, scihed mjhed, sciimg mjimg, scidate mjdate, scicat mjcat from sci order by scidate DESC UNION ALL select TOP 7 gamcod mjcod, gamhed mjhed, gamimg mjimg, gamdate mjdate, gamcat mjcat from games order by gamdate DESC UNION ALL select TOP 7 spcod mjcod, sphed mjhed, spimg mjimg, spdate mjdate, spcat mjcat from sports order by spdate DESC UNION ALL select TOP 7 entercod mjcod, enterhed mjhed, enterimg mjimg, enterdate mjdate, entercat mjcat from enter order by enterdate DESC UNION ALL select TOP 7 appcod mjcod, apphed mjhed, appimg mjimg, appdate mjdate, appcat mjcat from app order by appdate DESC) T order by mjdate DESC";
        SqlDataAdapter adp = new SqlDataAdapter(qry, ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
        DataSet ds = new DataSet();
        adp.Fill(ds);
        DataRowView r;
        r = ds.Tables[0].DefaultView[0];
        lcod1.Text = r["mjcod"].ToString();
        limg.ImageUrl = r["mjimg"].ToString();
        lhed1.Text = r["mjhed"].ToString();
        limg.AlternateText = lhed1.Text + " - KNine Vox";
        r = ds.Tables[0].DefaultView[1];
        lcod2.Text = r["mjcod"].ToString();
        lhed2.Text = r["mjhed"].ToString();
        r = ds.Tables[0].DefaultView[2];
        lcod3.Text = r["mjcod"].ToString();
        lhed3.Text = r["mjhed"].ToString();
        r = ds.Tables[0].DefaultView[3];
        lcod4.Text = r["mjcod"].ToString();
        lhed4.Text = r["mjhed"].ToString();
        r = ds.Tables[0].DefaultView[4];
        lcod5.Text = r["mjcod"].ToString();
        lhed5.Text = r["mjhed"].ToString();
        r = ds.Tables[0].DefaultView[5];
        lcod6.Text = r["mjcod"].ToString();
        lhed6.Text = r["mjhed"].ToString();
        r = ds.Tables[0].DefaultView[6];
        lcod7.Text = r["mjcod"].ToString();
        lhed7.Text = r["mjhed"].ToString();
    }
    private void mostPopular()
    {
        string qry = "select Top 4 fecod, fehed, fecat, tcod, fcat FROM(select techcod fecod, techhed fehed, techcat fecat from tech UNION ALL select scicod fecod, scihed fehed, scicat fecat from sci UNION ALL select gamcod fecod, gamhed fehed, gamcat fecat from games UNION ALL select spcod fecod, sphed fehed, spcat fecat from sports UNION ALL select entercod fecod, enterhed fehed, entercat fecat from enter UNION ALL select appcod fecod, apphed fehed, appcat fecat from app) T, featured where tcod = fecod AND fcat = fecat order by fcod ASC";
        SqlDataAdapter adp = new SqlDataAdapter(qry, ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
        DataSet ds = new DataSet();
        adp.Fill(ds);
        DataRowView r;
        r = ds.Tables[0].DefaultView[0];
        mcod1.Text = r["fecod"].ToString();
        mhed1.Text = r["fehed"].ToString();
        r = ds.Tables[0].DefaultView[1];
        mcod2.Text = r["fecod"].ToString();
        mhed2.Text = r["fehed"].ToString();
        r = ds.Tables[0].DefaultView[2];
        mcod3.Text = r["fecod"].ToString();
        mhed3.Text = r["fehed"].ToString();
        r = ds.Tables[0].DefaultView[3];
        mcod4.Text = r["fecod"].ToString();
        mhed4.Text = r["fehed"].ToString();
    }
    private string Author1(int autcod)
    {
        String qry1 = "select name from author where cod = " + autcod;
        SqlDataAdapter adp1 = new SqlDataAdapter(qry1, ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
        DataSet ds1 = new DataSet();
        adp1.Fill(ds1);
        DataRowView r1;
        r1 = ds1.Tables[0].DefaultView[0];
        String name = r1["name"].ToString();
        return name;
    }
    protected void search_button_Click(object sender, EventArgs e)
    {
        string txt = inpt_search.Value;
        Response.Redirect("Search" + "-" + txt);
    }

    protected void newsletter_Click(object sender, EventArgs e)
    {
        SqlConnection con = new SqlConnection();
        con.ConnectionString = ConfigurationManager.ConnectionStrings["cn"].ConnectionString;
        if (con.State == ConnectionState.Closed)
        {
            con.Open();
        }
        try
        {
            SqlCommand cmd = new SqlCommand("insnws", con);
            cmd.CommandType = CommandType.StoredProcedure;

            cmd.Parameters.Add("@email", SqlDbType.VarChar).Value = email1.Value;
            cmd.ExecuteNonQuery();
            cmd.Dispose();
            Label3.Text = "Successfully scbscribed";
            newsletter.Visible = false;
            email1.Visible = false;
        }
        catch (Exception ex)
        {
            Label3.Text = "Sorry, something went wrong, please try again later";
        }
        finally
        {
            con.Close();
        }
    }
}